name: Teo
rules:
  - when:
      red: 1
      green: 0
      blue: 0
      black: 0
    image: pinguino.png
    text: null
  - when:
      red: 0
      green: 1
      blue: 0
      black: 0
    image: roca (2).png
    text: null
  - when:
      red: 0
      green: 0
      blue: 1
      black: 0
    image: sardina.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 0
      black: 1
    image: teo y comida.png
    text: null
  - when:
      red: '*'
      green: '*'
      blue: '*'
      black: '*'
    image: fondo.png
    text: null
